// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4zUdbsUFLo5xzkDhgYk2QGl6-Zya5Lco',
    appId: '1:238899143994:web:c7883b9b00a898d2ba9c03',
    messagingSenderId: '238899143994',
    projectId: 'interview-f7eff',
    authDomain: 'interview-f7eff.firebaseapp.com',
    storageBucket: 'interview-f7eff.firebasestorage.app',
    measurementId: 'G-J4MW578G0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0N4VSUMXkKVFR_eWykLPfx5w1c0GDNIk',
    appId: '1:238899143994:android:edacc7ee153b212fba9c03',
    messagingSenderId: '238899143994',
    projectId: 'interview-f7eff',
    storageBucket: 'interview-f7eff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlg1YxFE3jXkDFVBo31cWIBN7NGuUr7Q',
    appId: '1:238899143994:ios:9cfa7848ddad5121ba9c03',
    messagingSenderId: '238899143994',
    projectId: 'interview-f7eff',
    storageBucket: 'interview-f7eff.firebasestorage.app',
    androidClientId: '238899143994-ag12s83cs1b5vfv9mmfdnbdrn9jkljgc.apps.googleusercontent.com',
    iosClientId: '238899143994-pshvpto1iq825b3a531q3p5thlfo11st.apps.googleusercontent.com',
    iosBundleId: 'com.example.vip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwlg1YxFE3jXkDFVBo31cWIBN7NGuUr7Q',
    appId: '1:238899143994:ios:9cfa7848ddad5121ba9c03',
    messagingSenderId: '238899143994',
    projectId: 'interview-f7eff',
    storageBucket: 'interview-f7eff.firebasestorage.app',
    androidClientId: '238899143994-ag12s83cs1b5vfv9mmfdnbdrn9jkljgc.apps.googleusercontent.com',
    iosClientId: '238899143994-pshvpto1iq825b3a531q3p5thlfo11st.apps.googleusercontent.com',
    iosBundleId: 'com.example.vip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4zUdbsUFLo5xzkDhgYk2QGl6-Zya5Lco',
    appId: '1:238899143994:web:86f0457b9a21bb4eba9c03',
    messagingSenderId: '238899143994',
    projectId: 'interview-f7eff',
    authDomain: 'interview-f7eff.firebaseapp.com',
    storageBucket: 'interview-f7eff.firebasestorage.app',
    measurementId: 'G-KD9WT5LRK4',
  );
}
